Error:
qlite3.OperationalError: unable to open database file
peewee.OperationalError: unable to open database file

Reason:
Something was written in a wrong way in db

Solution:
Use the last copy in "archived" folder. Replace "podcasts.db" with the copy. It might happen that some data lost, which was
written in the faulty db in the same session. So additional duplicate check required after using db copy.\\
------------------------------------------------------------------------------------------------------------------------------
Error:
UnboundLocalError: local variable 'field2' referenced before assignment
in podcasts1_create_record.py

Reason:
template contained only one 856 field

Solution:
	Open "Assets"/"Templates" and find the name the script was stuck.
	Add another 856 as in example.
    <datafield ind1="4" ind2="2" tag="856">
      <subfield code="3">File host</subfield>
      <subfield code="u">&lt;insert page URL&gt;</subfield>
    </datafield>
------------------------------------------------------------------------------------------------------------------------------
Error:
xml.sax._exceptions.SAXParseException: Y:\ndha\pre-deposit_prod\LD_working\podcasts\assets\templates\mis_Podcast_NZ_history.xml:1:909: not well-formed

Reason:
checked template, found "&" as it is. "&" considered to be special character for xml and should be replaced.

Solution:
replaced & by &#38; which is it's html code in template

------------------------------------------------------------------------------------------------------------------------------
Error:
When add new  podcast did not pass further "NFO:root:'Content-Disposition' exists in headers but failed to parse "
from downloader_light_modified.

Reason:
Logic
if not downloader.message or (downloader.message and self.podcast_name in ["Kiwi birth tales", "Board matters"]):

From this  type or rss there is not info in "Content-Disposition"
It gives message in dowloader light modified, which does not allow to go further

Solution:
Add podcast name to exception list.	



----------------------------------------------------------------------------------------------------------------------------------
Error:
When add new podcast NoneType object has not attribure rstrip in harvester script.

Reason:
No episode_link from 
[{'length': '10154576', 'type': 'audio/mpeg', 'href': 'https://www.buzzsprout.com/2014336/11152051-wayfinding-pae-ora-with-chris-webber-minstd.mp3', 'rel': 'enclosure'}]

Solution:
Add podcast name to one of the exception list  of pocast_harvester script.
					if self.podcast_name in ["Taxpayer talk","Board matters"] and not self.episode_link:
						self.episode_link = self.episode_download_link.split(".mp3")[0]
if self.podcast_name in ["Paige's space","Kelli from the Tron","Top writers radio show", "Dont give up your day job","Motherness","Kiwi birth tales","Board matters"]:
	self.episode_link = self.podcast_url

It will assign podcast url as episode link or download link as episode link. Depends on list.

----------------------------------------------------------------------------------------------------------------------------------

Error:
my_podcast_name = list(podcasts_dict.keys())[0]  list of indeces out of range

Reason:
podcasts_dict is empty

Solution:
Make sure that all titles uncommented

------------------------------------------------------------------------------------------------------------------------------------
Error:

Update_database_from_spreadsheetand_delete_row
    f100 = my_row[9]
IndexError: list index out of range

Reason:
First sheet in google spreadsheet is not main one.

Solution:
Go to browser
https://docs.google.com/spreadsheets/d/147Rdj_oxaAuJjj82YgYwwL6CqHdMh7s6ay3Ackrhq5c/edit#gid=0
Move main sheet on the first place and run script again

------------------------------------------------------------------------------------------------------------------------------------
Error:
  File "Y:\ndha\pre-deposit_prod\LD_working\podcasts\scripts\podcasts1_create_record.py", line 147, in parsing_added_fields
    indicator2 = indicators[1]
IndexError: string index out of range

Reason:
Cataloguers put incorrect data

Solution:
Uncomment 
		for fld in additional_fields_list:
			#print(fld)
in create_record script to see where is the  error.

use print_out script to update this field with correct information using existing for loops 

Example:
podcasts = Podcast.select()
for pod in podcasts:
	episodes = Episode.select().where(Episode.podcast==pod.id)
	for ep in episodes:
		if ep.f700_first == ".":
			print(ep.episode_title)
			q = Episode.update(f700_first= None).where(Episode.id==ep.id)
			q.execute()

------------------------------------------------------------------------------------------------------------------------------------
Error:

  File "Y:\ndha\pre-deposit_prod\LD_working\podcasts\scripts\podcasts.py", line 419, in update_database_from_spreadsheetand_delete_row
    f100 = my_row[9]
IndexError: list index out of range

Reason:
First sheet in google spreadsheet is not main one.

Solution:
Go to browser
https://docs.google.com/spreadsheets/d/147Rdj_oxaAuJjj82YgYwwL6CqHdMh7s6ay3Ackrhq5c/edit#gid=0
Move main sheet on the first place and run script again

------------------------------------------------------------------------------------------------------------------------------------
Error:



